### PR TITLE
Updated query and a bug fix for an edge case

### PR DESCRIPTION
**Pull request by ryanrolds**
Contains Chris Ritzo's query adjustments and a bug fix that handles an edge case with running the import for the first time (nil last).

### CODE REVIEW

**Comment by ryanrolds** [comment]
I just noticed that the lat and long is the query is different.

**Comment by critzo** [comment]
Good catch @ryanolds 
The original lat long coordinates are the box around Louisville and the ones in the pr are for Lane County or Oregon. 

I can send you a PR for `ryanrolds:mlab_query_adjustment` sometime tomorrow.

**Comment by ryanrolds** [comment]
@critzo I updated the PR to use the Louisville bounding box.

**Comment by ryanrolds** [comment]
@schnuerle There is a bug in the date format for `UTC_date_time`, it should be `%F %H:%m:%S UTC`.

**Comment by ryanrolds** [comment]
@critzo See above

**Pull request merged**
